### PR TITLE
docs: cleanse stale instructions

### PR DESCRIPTION
**Pull request by dgschwindturo**
These instructions were clearly out of date when it came to `golangci-lint`, which was upgraded earlier today via PR against `packer-github-actions-general` repo. Changes made here are speculative and require close review from @shakefu before we should consider merging these changes. I suspect more tweaks after @shakefu initial review.

### CODE REVIEW

**Comment by dgschwindturo** [comment]
I will mark this as draft until @shakefu gives me some feedback.

**Review by shakefu — CHANGES_REQUESTED** [review]
Was the containers directory removed by mistake? This would be a backwards-incompatible/breaking change. The hooks configuration still references those containers.

**Comment by dgschwindturo** [comment]
Could be @shakefu . Certainly the container for `golangci-lint` is no longer needed since that hook is baked into the AMI via `packer-github-actions-general`. Which of those containers need to be retained?

**Comment by dgschwindturo** [comment]
These changes are too far off, I will just close this PR and we will try again with a different PR.

**Pull request closed without merging**
