### PR TITLE
DEVOPS-9767: Use regular semantic-release for turo pre-commit-hooks

### PR DESCRIPTION
**Pull request by tagoro9**
**Description**

Use open-turo actions for releases and linting

Fixes [#DEVOPS-9767](https://team-turo.atlassian.net//browse/DEVOPS-9767)

**Changes**

* ci: update release and ci workflow to latest standards

🚀 PR created with [fotingo](https://github.com/tagoro9/fotingo)

### CODE REVIEW

**Review by dgschwindturo — APPROVED** [review]
Happy to give it a try!

**Review by greenkiwi — APPROVED** [review]

**Comment by tagoro9** [comment]
The beta release failed. Seeing why https://github.com/turo/pre-commit-hooks/actions/runs/6054654947

**Comment by tagoro9** [comment]
Found the issue. The low level action does not default any extra-plugin

**Comment by tagoro9** [comment]
Beta releases work now @dgschwindturo https://github.com/turo/pre-commit-hooks/releases/tag/v3.5.9-beta-devops-9767-1693608812121.1

**Pull request merged**
